"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "fi";

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ─── NAVBAR ────────────────────────────────────────────────────
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.equipment": "Equipment",
    "nav.careers": "Careers",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.requestQuote": "Request Quote",
    "nav.companyHistory": "Company History",
    "nav.companyHistory.desc": "Our journey since 2008",
    "nav.leadership": "Leadership",
    "nav.leadership.desc": "Meet the executive team",
    "nav.safety": "Safety & Standards",
    "nav.safety.desc": "Safety first, always",
    "nav.certifications": "Certifications",
    "nav.certifications.desc": "ISO and local credentials",
    "nav.commercial": "Commercial",
    "nav.commercial.desc": "High-rise, office blocks & retail hubs",
    "nav.residential": "Residential",
    "nav.residential.desc": "Premium custom housing & apartments",
    "nav.industrial": "Industrial",
    "nav.industrial.desc": "Factories, warehouses & processing plants",
    "nav.infrastructure": "Infrastructure",
    "nav.infrastructure.desc": "Bridges, roads & transit connections",
    "nav.renovation": "Renovation",
    "nav.renovation.desc": "Modernizing & upgrading structures",
    "nav.projectManagement": "Project Management",
    "nav.projectManagement.desc": "End-to-end site oversight & logistics",
    "nav.allPortfolio": "All Portfolio",
    "nav.allPortfolio.desc": "Explore our diverse construction cases",
    "nav.commercialCases": "Commercial Cases",
    "nav.commercialCases.desc": "Modern business parks & malls",
    "nav.industrialInstallations": "Industrial Installations",
    "nav.industrialInstallations.desc": "Heavy engineering achievements",
    "nav.residentialSpaces": "Residential Spaces",
    "nav.residentialSpaces.desc": "Architectural residential landmarks",
    "nav.megaFooterText": "Need customized technical planning in Finland?",
    "nav.megaFooterCta": "Consult an expert",

    // ─── HOME PAGE ─────────────────────────────────────────────────
    "hero.badge": "Pioneering Engineering & Construction · Finland",
    "hero.h1a": "Building",
    "hero.h1b": "Finland's",
    "hero.h1c": "Future",
    "hero.desc": "From complex industrial facilities to luxury waterfront properties, Rakentra Works engineering guarantees precision, structural innovation, and safety under the toughest Nordic conditions.",
    "hero.viewProjects": "View Projects",
    "hero.requestQuote": "Request Quote",
    "hero.trust": "client satisfaction · 650+ projects",
    // Statistics
    "stat.0.label": "Years in Operation",
    "stat.0.desc": "Delivering excellence since 2008",
    "stat.1.label": "Projects Completed",
    "stat.1.desc": "Across commercial, residential & civil sectors",
    "stat.2.label": "Expert Professionals",
    "stat.2.desc": "HSE-certified engineers and builders",
    "stat.3.label": "Client Satisfaction",
    "stat.3.desc": "Based on post-completion RALA audits",
    // Services section
    "home.services.badge": "WHAT WE BUILD",
    "home.services.h1": "Our Construction",
    "home.services.h2": "Services",
    "home.services.link": "Explore Detailed Services",
    "home.services.cardCta": "Process & Benefits",
    // Featured Projects section
    "home.projects.badge": "CASE STUDIES",
    "home.projects.h1": "Featured",
    "home.projects.h2": "Projects",
    "home.projects.link": "Browse Full Portfolio",
    "home.projects.budget": "Budget",
    "home.projects.location": "Location",
    "home.projects.year": "Year",
    "home.projects.client": "Client:",
    "home.projects.viewDetails": "View Details",
    // Why Rakentra section
    "home.why.badge": "OUR EDGE",
    "home.why.h1": "Why Finland Trusts",
    "home.why.h2": "Rakentra",
    "home.why.desc": "We combine robust engineering expertise, high-tech planning, and a rigid commitment to quality to construct lasting landmarks.",
    "why.0.title": "Nordic Winter Safety Protocols",
    "why.0.desc": "Our zero-accident policy is backed by custom safety training suited for freezing conditions, ice mitigation, and heavy machinery safety operations.",
    "why.1.title": "Uncompromising Quality Control",
    "why.1.desc": "As a RALA-certified contractor, every project phase goes through stringent material testing, density metrics, and structural integrity reviews.",
    "why.2.title": "Sustainable Innovation & BIM 3D",
    "why.2.desc": "We leverage Level 3 Building Information Modeling (BIM) to reduce waste by up to 15%, maximize thermal efficiency, and track carbon offsets.",
    "why.3.title": "On-Time & Within-Budget Guarantee",
    "why.3.desc": "Integrated scheduling systems sync material supply chains and workforce allocation to guarantee zero project hand-over delays.",
    // Testimonials section
    "home.testimonials.badge": "CLIENT TESTIMONIALS",
    "home.testimonials.h1": "Partnerships Formed",
    "home.testimonials.h2": "in Trust",
    "testimonial.0.quote": "Rakentra Works exceeded our expectations on the Helsinki Innovation Center. Their application of Level 3 BIM modeling resolved design clashes before framing, saving us weeks of on-site adjustments. A true engineering partner.",
    "testimonial.0.title": "Director of Infrastructure, Capital City Properties",
    "testimonial.1.quote": "Constructing a battery dryroom facility requires extreme precision. Rakentra's team managed the concrete vibrations isolation and humidity parameters flawlessly. Their Nordic winter safety operations are unmatched.",
    "testimonial.1.title": "VP of Engineering, Suomi Energy Solutions",
    "testimonial.2.quote": "The restoration of our Aura Riverfront property was a delicate balance of history and modern utility. Rakentra stabilized the foundation using micro-piles without compromising the protected facade. Highly recommended.",
    "testimonial.2.title": "Head of Project Delivery, Baltic Heritage Hotels Group",
    // Partners section
    "home.partners.label": "COLLABORATING WITH INDUSTRY LEADERS",
    // CTA section
    "home.cta.badge": "START YOUR PROJECT",
    "home.cta.h1": "Ready to Build Your Next",
    "home.cta.h2": "Landmark in Finland?",
    "home.cta.desc": "Discuss your technical blueprints, structural needs, and schedule parameters with our engineering team today. Turnkey project management or specialised sub-contracting.",
    "home.cta.btn1": "Consult Our Specialists",
    "home.cta.btn2": "Explore Capabilities",

    // ─── ABOUT PAGE ────────────────────────────────────────────────
    "about.hero.badge": "WHO WE ARE",
    "about.hero.h1": "Rakentra Works,",
    "about.hero.h2": "Finland's Engineering Force",
    "about.hero.desc": "18 years of precision engineering, structural innovation, and safety-first delivery across Finland's most demanding construction environments.",
    "about.mission.badge": "OUR FOUNDATION",
    "about.mission.h": "Mission & Vision",
    "about.mission.title": "Our Mission",
    "about.mission.desc": "To engineer Finland's built environment with unwavering precision and safety standards, building structures that outlast generations and serve communities across the nation.",
    "about.vision.title": "Our Vision",
    "about.vision.desc": "To be Finland's most respected construction company — one where quality engineering, sustainable practices, and client trust are the foundation of every project.",
    "about.history.badge": "MILESTONES",
    "about.history.h": "Our Journey",
    "about.history.sub": "From a modest engineering consultancy to one of Finland's leading construction organizations.",
    "about.safety.badge": "HEALTH & SAFETY",
    "about.safety.h": "Safety is Non-Negotiable",
    "about.safety.desc": "Construction requires strict site safety operations, especially in cold, dark Finnish winters. We enforce daily HSE walkthroughs, regular tool-box talks, and provide cold-weather safety kits to all personnel on-site.",
    "about.safety.zeroTitle": "Zero Accident Target",
    "about.safety.zeroDesc": "We operate under a strict zero-tolerance accident policy. All personnel undergo site-specific induction, and safety documentation is maintained through our digital HSE management system.",
    "about.certs.badge": "CREDENTIALS",
    "about.certs.h": "Our Certifications",
    "about.certs.agency": "Issuing Agency",
    "about.certs.valid": "Valid Until",
    "about.leadership.badge": "LEADERSHIP",
    "about.leadership.h": "Executive Team",
    "about.leadership.sub": "Experienced professionals steering Finland's construction industry forward.",
    "about.cta.h": "Partner With Finland's Trusted Builder",
    "about.cta.desc": "Whether you're planning a commercial office tower, residential complex, or a large-scale infrastructure project, Rakentra Works is ready to deliver.",
    "about.cta.btn1": "Start Your Project",
    "about.cta.btn2": "Download Company Profile",

    // ─── SERVICES PAGE ─────────────────────────────────────────────
    "services.hero.badge": "WHAT WE DO",
    "services.hero.h1": "Our Construction Capabilities",
    "services.hero.desc": "We deliver turn-key structural construction projects across Finland, standardizing safety protocols and digital coordinate modeling to achieve zero-defect handovers.",
    "services.division": "DIVISION",
    "services.benefits": "Key Technical Benefits",
    "services.process": "Our Execution Process",
    "services.step": "Step",
    "services.cta": "Consult Division Specialist",
    "services.certs.h": "RALA Quality Certification is standard in all divisions",
    "services.certs.desc": "We adhere strictly to Finnish building regulations (Rakentamismääräyskokoelma) and structural Eurocodes, validating air-tightness, material densities, and heat insulation limits.",
    "services.certs.label": "REGULATORY REGISTRATION",
    "services.certs.reg": "RALA Audited #28471",

    // ─── PROJECTS PAGE ─────────────────────────────────────────────
    "projects.hero.badge": "OUR PORTFOLIO",
    "projects.hero.h1": "Construction",
    "projects.hero.h2": "Projects",
    "projects.hero.desc": "Explore our portfolio of precision-engineered commercial, industrial, residential and infrastructure projects across Finland.",
    "projects.filter.all": "All Projects",
    "projects.filter.commercial": "Commercial",
    "projects.filter.residential": "Residential",
    "projects.filter.industrial": "Industrial",
    "projects.filter.infrastructure": "Infrastructure",
    "projects.filter.renovation": "Renovation",
    "projects.budget": "Budget",
    "projects.area": "Area",
    "projects.completion": "Completion",
    "projects.viewCase": "View Case Study",
    "projects.empty": "No projects in this category yet.",

    // ─── PROJECT DETAIL ────────────────────────────────────────────
    "project.back": "Back to Portfolio",
    "project.overview": "Project Overview",
    "project.gallery": "Project Media Gallery",
    "project.timeline": "Construction Timeline",
    "project.outcomes": "Key Project Outcomes",
    "project.specs": "Technical Specifications",
    "project.client": "Client",
    "project.area": "Floor Area",
    "project.budget": "Project Budget",
    "project.completion": "Completion Date",
    "project.category": "Category",
    "project.location": "Location",
    "project.cta": "Start a Similar Project",
    "project.notFound.h": "Project Not Found",
    "project.notFound.desc": "The project study you are searching for does not exist or has been archived.",

    // ─── CONTACT PAGE ─────────────────────────────────────────────
    "contact.hero.badge": "GET IN TOUCH",
    "contact.hero.h1": "Let's Build",
    "contact.hero.h2": "Something Great",
    "contact.hero.desc": "Tell us about your project requirements, timeline, and specifications. Our technical team typically responds within 24 hours.",
    "contact.estimator.badge": "COST ESTIMATOR",
    "contact.estimator.h": "Project Cost Estimator",
    "contact.estimator.desc": "Get a preliminary estimate for your project before reaching out.",
    "contact.estimator.type": "Construction Type",
    "contact.estimator.area": "Floor Area (m²)",
    "contact.estimator.quality": "Quality Specification",
    "contact.estimator.quality.standard": "Standard Specification",
    "contact.estimator.quality.premium": "Premium Specification",
    "contact.estimator.quality.luxury": "Luxury / Bespoke",
    "contact.estimator.result": "Estimated Budget Range",
    "contact.estimator.note": "Preliminary estimate only. Final pricing requires a site survey and detailed specification review.",
    "contact.offices.badge": "OUR OFFICES",
    "contact.offices.h": "Regional Offices",
    "contact.offices.cta": "Book a Site Visit",
    "contact.form.badge": "PROJECT ENQUIRY",
    "contact.form.h": "Send Project Brief",
    "contact.form.name": "Full Name *",
    "contact.form.company": "Company / Organisation",
    "contact.form.email": "Email Address *",
    "contact.form.phone": "Phone Number",
    "contact.form.type": "Project Type *",
    "contact.form.budget": "Estimated Budget",
    "contact.form.location": "Project Location (City) *",
    "contact.form.message": "Project Brief & Requirements *",
    "contact.form.submit": "Send Project Brief",
    "contact.form.submitting": "Sending…",
    "contact.form.success.h": "Brief Received!",
    "contact.form.success.desc": "Our team will review your project requirements and contact you within 24 hours.",
    "contact.map.badge": "OFFICE LOCATION",
    "contact.map.h": "Find Our Offices",
    "contact.hero.h": "Let's Coordinate Your Project",
    "contact.estimator.specs": "Design Specifications",
    "contact.estimator.division": "Project Division",
    "contact.estimator.qualityLabel": "Quality & Compliance Standard",
    "contact.estimator.extras": "Extra Engineering Add-ons",
    "contact.estimator.output": "Estimated Output",
    "contact.estimator.applyBtn": "Apply Estimates to Form",
    "contact.emergency.label": "Site Emergency Hotline",
    "contact.emergency.desc": "For active construction site safety incidents, heavy machinery blockages, or structural integrity hazards in Finland, call our HSE supervisor hotline immediately.",
    "contact.form.scope": "Project Specifications & Scope Details",
    "contact.form.category": "Project Category",
    "contact.form.successTitle": "Proposal Inquiry Received",
    "contact.form.successDesc": "Thank you. Your project blueprints and budget parameters have been logged. An estimator will contact you within 24 hours.",
    "blog.hero.h": "Rakentra Insights & News",

    // ─── BLOG PAGE ────────────────────────────────────────────────
    "blog.hero.badge": "RAKENTRA INSIGHTS",
    "blog.hero.h1": "Engineering",
    "blog.hero.h2": "Knowledge Hub",
    "blog.hero.desc": "Technical insights, case studies, and Nordic construction trends from our expert engineering team.",
    "blog.filter.all": "All Articles",
    "blog.filter.trends": "Trends",
    "blog.filter.caseStudy": "Case Study",
    "blog.filter.news": "News",
    "blog.filter.insights": "Insights",
    "blog.readMore": "Read Article",
    "blog.readTime": "read",
    "blog.empty": "No articles in this category yet.",

    // ─── CAREERS PAGE ─────────────────────────────────────────────
    "careers.hero.badge": "JOIN OUR TEAM",
    "careers.hero.h1": "Build Your Career",
    "careers.hero.h2": "With Finland's Best",
    "careers.hero.desc": "We're looking for skilled engineers, site managers, and construction professionals to help us deliver world-class projects across Finland.",
    "careers.benefits.badge": "WHY RAKENTRA",
    "careers.benefits.h": "Why Work With Us",
    "careers.positions.badge": "CAREER OPPORTUNITIES",
    "careers.positions.h": "Current Open Positions",
    "careers.positions.desc": "Apply today to join our regional office boards and site development teams.",
    "careers.positions.applyBtn": "Apply Now",
    "careers.positions.responsibilities": "Responsibilities",
    "careers.positions.requirements": "Requirements",
    "careers.recruitment.badge": "PROCESS",
    "careers.recruitment.h": "Our Recruitment Process",
    "careers.form.badge": "APPLICATION FORM",
    "careers.form.name": "Full Name *",
    "careers.form.email": "Email Address *",
    "careers.form.phone": "Phone Number",
    "careers.form.linkedin": "LinkedIn Profile URL",
    "careers.form.message": "Cover Letter / Message *",
    "careers.form.submit": "Submit Application",
    "careers.form.submitting": "Submitting…",
    "careers.form.close": "Close",

    // ─── EQUIPMENT PAGE ───────────────────────────────────────────
    "equipment.hero.badge": "HEAVY MACHINERY",
    "equipment.hero.h1": "Our Fleet &",
    "equipment.hero.h2": "Technology",
    "equipment.hero.desc": "Rakentra Works maintains an extensive fleet of modern construction machinery and deploys leading smart-site technology to ensure precision, speed, and safety on every project.",
    "equipment.fleet.badge": "MACHINERY FLEET",
    "equipment.fleet.h": "Active Machinery Fleet",
    "equipment.fleet.desc": "Owned and maintained to highest operational standards — eliminating sub-hire delays.",
    "equipment.fleet.col.name": "Machinery Name",
    "equipment.fleet.col.category": "Category",
    "equipment.fleet.col.spec": "Technical Specifications",
    "equipment.fleet.col.count": "In Service",
    "equipment.fleet.units": "units",
    "equipment.tech.badge": "INNOVATION",
    "equipment.tech.h": "BIM & Smart Site Technology",
    "equipment.tech.desc": "We leverage cloud collaboration and IoT telemetry to reduce design conflicts, monitor materials in real time, and guarantee energy metrics.",
    "equipment.cta.h": "Need Specialised Equipment on Your Project?",
    "equipment.cta.desc": "Our fleet is available for client-specific project deployment. Contact our logistics team to check machinery availability.",
    "equipment.cta.btn": "Check Fleet Availability",

    // ─── FOOTER ───────────────────────────────────────────────────
    "footer.aboutText": "State-of-the-art building infrastructure, residential engineering, and industrial spaces across Finland. Standardizing safety and modernizing engineering since 2008.",
    "footer.cert1": "RALA Certified Contractor (Finland)",
    "footer.cert2": "ISO 9001 & ISO 14001 Standards",
    "footer.companyTitle": "Company",
    "footer.servicesTitle": "Services",
    "footer.contactTitle": "Get in Touch",
    "footer.officeLabel": "HELSINKI HEADQUARTERS",
    "footer.officeAddress": "Mannerheimintie 12A, 00100 Helsinki, Finland",
    "footer.newsletterLabel": "Stay updated on industry insights",
    "footer.newsletterPlaceholder": "Your email address",
    "footer.copyright": "Rakentra Works. All rights reserved. Registered Finnish Business ID: FI2847192-3.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.locations": "Contact Locations",
    "footer.company.about": "About Us",
    "footer.company.leadership": "Leadership",
    "footer.company.safety": "Safety Standards",
    "footer.company.certs": "Certifications",
    "footer.company.careers": "Careers",
    "footer.services.commercial": "Commercial Construction",
    "footer.services.residential": "Residential Building",
    "footer.services.industrial": "Industrial Facilities",
    "footer.services.infrastructure": "Infrastructure Projects",
    "footer.services.renovation": "Renovations & Retrofits",
    "footer.services.pm": "Project Management",
  },

  fi: {
    // ─── NAVBAR ────────────────────────────────────────────────────
    "nav.home": "Etusivu",
    "nav.about": "Tietoa meistä",
    "nav.services": "Palvelut",
    "nav.projects": "Projektit",
    "nav.equipment": "Kalusto",
    "nav.careers": "Ura",
    "nav.blog": "Blogi",
    "nav.contact": "Yhteystiedot",
    "nav.requestQuote": "Pyydä tarjous",
    "nav.companyHistory": "Yrityksen historia",
    "nav.companyHistory.desc": "Matkamme vuodesta 2008",
    "nav.leadership": "Johtoryhmä",
    "nav.leadership.desc": "Tapaa johtotiimi",
    "nav.safety": "Turvallisuus & standardit",
    "nav.safety.desc": "Turvallisuus aina ensin",
    "nav.certifications": "Sertifioinnit",
    "nav.certifications.desc": "ISO- ja paikalliset sertifikaatit",
    "nav.commercial": "Toimitilat",
    "nav.commercial.desc": "Pilvenpiirtäjät, toimistot & kauppakeskukset",
    "nav.residential": "Asuinrakennukset",
    "nav.residential.desc": "Laadukkaat asunnot & kerrostalot",
    "nav.industrial": "Teollisuus",
    "nav.industrial.desc": "Tehtaat, varastot & tuotantolaitokset",
    "nav.infrastructure": "Infrastruktuuri",
    "nav.infrastructure.desc": "Sillat, tiet & liikennejärjestelmät",
    "nav.renovation": "Saneeraus",
    "nav.renovation.desc": "Rakennusten modernisointi & kunnostus",
    "nav.projectManagement": "Projektinhallinta",
    "nav.projectManagement.desc": "Kokonaisvaltainen työmaavalvonta & logistiikka",
    "nav.allPortfolio": "Kaikki projektit",
    "nav.allPortfolio.desc": "Tutustu monipuolisiin rakennusprojekteihimme",
    "nav.commercialCases": "Toimitilakohteet",
    "nav.commercialCases.desc": "Modernit yrityspuistot & ostoskeskukset",
    "nav.industrialInstallations": "Teollisuusasennukset",
    "nav.industrialInstallations.desc": "Raskaan tekniikan saavutukset",
    "nav.residentialSpaces": "Asuintilat",
    "nav.residentialSpaces.desc": "Arkkitehtoniset asuinalueet",
    "nav.megaFooterText": "Tarvitsetko räätälöityä teknistä suunnittelua Suomessa?",
    "nav.megaFooterCta": "Ota yhteyttä asiantuntijaan",

    // ─── HOME PAGE ─────────────────────────────────────────────────
    "hero.badge": "Edelläkävijä insinööritieteissä & rakentamisessa · Suomi",
    "hero.h1a": "Rakennetaan",
    "hero.h1b": "Suomen",
    "hero.h1c": "Tulevaisuus",
    "hero.desc": "Monimutkaisista teollisuuslaitoksista luksusrantakiinteistöihin — Rakentra Works takaa tarkkuuden, rakenteellisen innovaation ja turvallisuuden vaativimmissakin pohjoismaisissa olosuhteissa.",
    "hero.viewProjects": "Katso projektit",
    "hero.requestQuote": "Pyydä tarjous",
    "hero.trust": "asiakastyytyväisyys · 650+ projektia",
    // Statistics
    "stat.0.label": "Toimintavuotta",
    "stat.0.desc": "Huippulaatuista toimintaa vuodesta 2008",
    "stat.1.label": "Valmistunutta projektia",
    "stat.1.desc": "Kaupallisella, asuin- ja siviilisektorilla",
    "stat.2.label": "Asiantuntijaa",
    "stat.2.desc": "HSE-sertifioituja insinöörejä ja rakentajia",
    "stat.3.label": "Asiakastyytyväisyys",
    "stat.3.desc": "RALA-auditointitulosten perusteella",
    // Services section
    "home.services.badge": "MITÄ RAKENNAMME",
    "home.services.h1": "Rakennuspalvelumme",
    "home.services.h2": "",
    "home.services.link": "Tutustu palveluihin tarkemmin",
    "home.services.cardCta": "Prosessi & hyödyt",
    // Featured Projects section
    "home.projects.badge": "TAPAUSTUTKIMUKSET",
    "home.projects.h1": "Esitellyt",
    "home.projects.h2": "Projektit",
    "home.projects.link": "Selaa koko portfoliota",
    "home.projects.budget": "Budjetti",
    "home.projects.location": "Sijainti",
    "home.projects.year": "Vuosi",
    "home.projects.client": "Asiakas:",
    "home.projects.viewDetails": "Katso tiedot",
    // Why Rakentra section
    "home.why.badge": "KILPAILUETUMME",
    "home.why.h1": "Miksi Suomi luottaa",
    "home.why.h2": "Rakentraan",
    "home.why.desc": "Yhdistämme vahvan insinööriosaamisen, huipputeknisen suunnittelun ja tiukan laadun valvonnan rakentaaksemme kestäviä maamerkkejä.",
    "why.0.title": "Pohjoismainen talviturvallisprotokolla",
    "why.0.desc": "Nollatapaturmapolitiikkamme tueksi on räätälöity turvallisuuskoulutus pakkasiin, jäänhallintaan ja raskaskonevalmius-toimintaan.",
    "why.1.title": "Kompromissitonta laadunhallintaa",
    "why.1.desc": "RALA-sertifioituna urakoitsijana jokainen projektin vaihe läpäisee tiukan materiaalitestauksen, tiheysmetriikat ja rakenteen eheyden tarkastukset.",
    "why.2.title": "Kestävä innovaatio & BIM 3D",
    "why.2.desc": "Hyödynnämme tason 3 rakennusten tietomallintamista (BIM) vähentääksemme hukkaa jopa 15 %, maksimoidaksemme lämpötehokkuuden ja seurataksemme hiilidioksidikompensaatioita.",
    "why.3.title": "Aikataulussa ja budjetissa – aina",
    "why.3.desc": "Integroidut aikataulutusjärjestelmät synkronoivat materiaalitoimitusketjut ja työvoimaresursoinnin takaamaan nollaviivästykset projektin luovutuksessa.",
    // Testimonials section
    "home.testimonials.badge": "ASIAKASPALAUTTEET",
    "home.testimonials.h1": "Kumppanuuksia",
    "home.testimonials.h2": "luotettavuuden pohjalta",
    "testimonial.0.quote": "Rakentra Works ylitti odotuksemme Helsinki Innovation Centerissä. Heidän tason 3 BIM-mallinnuksensa ratkaisi suunnitteluristiriidat ennen rungon asennusta, säästäen meiltä viikkoja kenttäkorjauksissa. Aito insinöörinen kumppani.",
    "testimonial.0.title": "Infrastruktuurijohtaja, Capital City Properties",
    "testimonial.1.quote": "Akkulaboratorion rakentaminen vaatii äärimmäistä tarkkuutta. Rakentran tiimi hallitsi betonin tärinäeristyksen ja kosteusparametrit moitteettomasti. Heidän pohjoismaiset talviturvallisuusoperaationsa ovat vertaansa vailla.",
    "testimonial.1.title": "Teknologiajohtaja, Suomi Energy Solutions",
    "testimonial.2.quote": "Aura Riverfront -kiinteistömme restaurointi oli herkkää tasapainoilua historian ja modernin käyttökelpoisuuden välillä. Rakentra stabiloi perustan mikro-paalulla vaarantamatta suojeltua julkisivua. Lämpimästi suositeltavissa.",
    "testimonial.2.title": "Projektitoimitusjohtaja, Baltic Heritage Hotels Group",
    // Partners section
    "home.partners.label": "YHTEISTYÖSSÄ ALAN JOHTAJIEN KANSSA",
    // CTA section
    "home.cta.badge": "ALOITA PROJEKTISI",
    "home.cta.h1": "Valmiina rakentamaan seuraavan",
    "home.cta.h2": "maamerkki Suomeen?",
    "home.cta.desc": "Keskustele teknisistä suunnitelmistasi, rakenteellisista tarpeistasi ja aikataulustasi insinööriyksikkömme kanssa tänään. Avaimet käteen -projektinhallinta tai erikoistuneet aliurakat.",
    "home.cta.btn1": "Ota yhteyttä asiantuntijoihin",
    "home.cta.btn2": "Tutustu palveluihimme",

    // ─── ABOUT PAGE ────────────────────────────────────────────────
    "about.hero.badge": "KEITÄ OLEMME",
    "about.hero.h1": "Rakentra Works,",
    "about.hero.h2": "Suomen insinöörivoima",
    "about.hero.desc": "18 vuotta täsmällistä insinöörityötä, rakenteellista innovaatiota ja turvallisuusprioriteettia Suomen vaativimmissa rakennusympäristöissä.",
    "about.mission.badge": "PERUSTAMME",
    "about.mission.h": "Missio & visio",
    "about.mission.title": "Missiomme",
    "about.mission.desc": "Rakentaa Suomen rakennettua ympäristöä horjumattomalla tarkkuudella ja turvallisuusstandardeilla — rakenteitaan, jotka kestävät sukupolvet ja palvelevat yhteisöjä kaikkialla maassa.",
    "about.vision.title": "Visiomme",
    "about.vision.desc": "Olla Suomen arvostetuimpia rakennusyrityksiä — sellainen, jossa laadukas insinöörityö, kestävä kehitys ja asiakkaiden luottamus ovat jokaisen projektin perusta.",
    "about.history.badge": "VIRSTANPYLVÄÄT",
    "about.history.h": "Matkamme",
    "about.history.sub": "Vaatimattomasta insinööriosaamiskonsultista yhdeksi Suomen johtavista rakennusorganisaatioista.",
    "about.safety.badge": "TERVEYS & TURVALLISUUS",
    "about.safety.h": "Turvallisuudesta ei tingitä",
    "about.safety.desc": "Rakentaminen vaatii tiukkaa työmaatuvallisuutta erityisesti kylminä, pimeinä suomalaisina talvina. Vaadimme päivittäisiä HSE-kierroksia, säännöllisiä työkalulaatikkokeskusteluja ja tarjoamme kylmänsuojakassin kaikille.",
    "about.safety.zeroTitle": "Nollatapaturmatavoite",
    "about.safety.zeroDesc": "Noudatamme tiukkaa nollatoleranssia tapaturmissa. Kaikki henkilöt käyvät työmaakohtaisen perehdytyksen, ja turvallisuusasiakirjat ylläpidetään digitaalisessa HSE-hallintajärjestelmässämme.",
    "about.certs.badge": "PÄTEVYYDET",
    "about.certs.h": "Sertifikaattimme",
    "about.certs.agency": "Myöntävä taho",
    "about.certs.valid": "Voimassa",
    "about.leadership.badge": "JOHTAJUUS",
    "about.leadership.h": "Johtoryhmä",
    "about.leadership.sub": "Kokeneet ammattilaiset, jotka vievät Suomen rakennusteollisuutta eteenpäin.",
    "about.cta.h": "Kumppaniksesi Suomen luotetuin rakentaja",
    "about.cta.desc": "Suunnittelitpa kaupallisen toimistotornin, asuinkompleksin tai laajan infrastruktuurihankkeen — Rakentra Works on valmis toimittamaan.",
    "about.cta.btn1": "Aloita projektisi",
    "about.cta.btn2": "Lataa yritysprofiili",

    // ─── SERVICES PAGE ─────────────────────────────────────────────
    "services.hero.badge": "MITÄ TEEMME",
    "services.hero.h1": "Rakennuspalvelumme",
    "services.hero.desc": "Toteutamme avaimet käteen -rakentamisprojekteja kaikkialla Suomessa standardoiden turvallisuusprotokollat ja digitaalinen koordinointimalli nollavirheluovutuksiin.",
    "services.division": "DIVISIOONA",
    "services.benefits": "Tekniset päähyödyt",
    "services.process": "Toteutusprosessimme",
    "services.step": "Vaihe",
    "services.cta": "Ota yhteyttä divisioonan asiantuntijaan",
    "services.certs.h": "RALA-laatusertifiointi on standardi kaikissa divisioonissa",
    "services.certs.desc": "Noudatamme tiukasti suomalaisia rakentamismääräyksiä (Rakentamismääräyskokoelma) ja rakenteellisia Eurokoodeja validoiden ilmatiiveyden, materiaalitiheydet ja lämpöeristysrajat.",
    "services.certs.label": "VIRANOMAISREKISTERÖINTI",
    "services.certs.reg": "RALA-tarkastettu nro 28471",

    // ─── PROJECTS PAGE ─────────────────────────────────────────────
    "projects.hero.badge": "PORTFOLIOMME",
    "projects.hero.h1": "Rakennus",
    "projects.hero.h2": "projektit",
    "projects.hero.desc": "Tutustu portfolioomme täsmällisesti suunnitelluista kaupallisista, teollisista, asuin- ja infrastruktuuriprojekteista kaikkialla Suomessa.",
    "projects.filter.all": "Kaikki projektit",
    "projects.filter.commercial": "Toimitilat",
    "projects.filter.residential": "Asuinrakennukset",
    "projects.filter.industrial": "Teollisuus",
    "projects.filter.infrastructure": "Infrastruktuuri",
    "projects.filter.renovation": "Saneeraus",
    "projects.budget": "Budjetti",
    "projects.area": "Pinta-ala",
    "projects.completion": "Valmistuminen",
    "projects.viewCase": "Katso tapaustutkimus",
    "projects.empty": "Ei projekteja tässä kategoriassa.",

    // ─── PROJECT DETAIL ────────────────────────────────────────────
    "project.back": "Takaisin portfolioon",
    "project.overview": "Projektin kuvaus",
    "project.gallery": "Projektin kuvagalleria",
    "project.timeline": "Rakentamisaikataulu",
    "project.outcomes": "Projektin päätulokset",
    "project.specs": "Tekniset tiedot",
    "project.client": "Asiakas",
    "project.area": "Kerrosala",
    "project.budget": "Projektibudjetti",
    "project.completion": "Valmistumispäivä",
    "project.category": "Kategoria",
    "project.location": "Sijainti",
    "project.cta": "Aloita vastaava projekti",
    "project.notFound.h": "Projektia ei löydy",
    "project.notFound.desc": "Etsimääsi projektianalyysiä ei ole olemassa tai se on arkistoitu.",

    // ─── CONTACT PAGE ─────────────────────────────────────────────
    "contact.hero.badge": "OTA YHTEYTTÄ",
    "contact.hero.h1": "Rakennetaan",
    "contact.hero.h2": "yhdessä jotain suurta",
    "contact.hero.desc": "Kerro meille projektivaatimuksistasi, aikataulustasi ja teknisistä erittelyistä. Tekniinen tiimimme vastaa tyypillisesti 24 tunnin kuluessa.",
    "contact.estimator.badge": "KUSTANNUSARVIO",
    "contact.estimator.h": "Projektin kustannusarvio",
    "contact.estimator.desc": "Pyydä alustava arvio projektillesi ennen yhteydenottoa.",
    "contact.estimator.type": "Rakennustyyppi",
    "contact.estimator.area": "Kerrosala (m²)",
    "contact.estimator.quality": "Laatuvaatimus",
    "contact.estimator.quality.standard": "Standardi",
    "contact.estimator.quality.premium": "Premium",
    "contact.estimator.quality.luxury": "Luksus / Räätälöity",
    "contact.estimator.result": "Arvioitu budjetti",
    "contact.estimator.note": "Vain alustava arvio. Lopullinen hinnoittelu edellyttää maastokatselmusta ja yksityiskohtaista erittelyn arviointia.",
    "contact.offices.badge": "TOIMISTOMME",
    "contact.offices.h": "Alueelliset toimistot",
    "contact.offices.cta": "Varaa maastokatsaus",
    "contact.form.badge": "PROJEKTIKYSELY",
    "contact.form.h": "Lähetä projektibrief",
    "contact.form.name": "Koko nimi *",
    "contact.form.company": "Yritys / Organisaatio",
    "contact.form.email": "Sähköpostiosoite *",
    "contact.form.phone": "Puhelinnumero",
    "contact.form.type": "Projektin tyyppi *",
    "contact.form.budget": "Arvioitu budjetti",
    "contact.form.location": "Projektin sijainti (kaupunki) *",
    "contact.form.message": "Projektibrief & vaatimukset *",
    "contact.form.submit": "Lähetä projektibrief",
    "contact.form.submitting": "Lähetetään…",
    "contact.form.success.h": "Brief vastaanotettu!",
    "contact.form.success.desc": "Tiimimme käy läpi projektivaatimuksesi ja ottaa yhteyttä 24 tunnin kuluessa.",
    "contact.map.badge": "TOIMISTON SIJAINTI",
    "contact.map.h": "Löydä toimistomme",
    "contact.hero.h": "Koordinoidaan projektisi",
    "contact.estimator.specs": "Suunnittelun erittelyt",
    "contact.estimator.division": "Projektin divisioona",
    "contact.estimator.qualityLabel": "Laatu- ja vaatimustenmukaisuusstandardi",
    "contact.estimator.extras": "Lisäinsinööriliitteet",
    "contact.estimator.output": "Arvioitu tulos",
    "contact.estimator.applyBtn": "Käytä arvioita lomakkeessa",
    "contact.emergency.label": "Työmaan hätälinja",
    "contact.emergency.desc": "Aktiivisten rakennustyömaiden turvallisuusonnettomuuksien, raskaiden koneiden esteiden tai rakenteen eheyshäiriöiden varalta Suomessa ota välittömästi yhteyttä HSE-valvojamme hätälinjaan.",
    "contact.form.scope": "Projektin erittelyt & laajuustiedot",
    "contact.form.category": "Projektikategoria",
    "contact.form.successTitle": "Ehdotuspyyntö vastaanotettu",
    "contact.form.successDesc": "Kiitos. Projektisuunnitelmasi ja budjettisi on kirjattu. Arvioijamme ottaa yhteyttä 24 tunnin kuluessa.",
    "blog.hero.h": "Rakentra Insights & Uutiset",

    // ─── BLOG PAGE ────────────────────────────────────────────────
    "blog.hero.badge": "RAKENTRA INSIGHTS",
    "blog.hero.h1": "Insinööriosaamisen",
    "blog.hero.h2": "tietopankki",
    "blog.hero.desc": "Teknisiä oivalluksia, tapaustutkimuksia ja pohjoismaisia rakennustrendejä asiantuntijainsinööriyksikköltämme.",
    "blog.filter.all": "Kaikki artikkelit",
    "blog.filter.trends": "Trendit",
    "blog.filter.caseStudy": "Tapaustutkimus",
    "blog.filter.news": "Uutiset",
    "blog.filter.insights": "Oivallukset",
    "blog.readMore": "Lue artikkeli",
    "blog.readTime": "lukuaika",
    "blog.empty": "Ei artikkeleita tässä kategoriassa.",

    // ─── CAREERS PAGE ─────────────────────────────────────────────
    "careers.hero.badge": "LIITY TIIMIIMME",
    "careers.hero.h1": "Rakenna urasi",
    "careers.hero.h2": "Suomen parhaan kanssa",
    "careers.hero.desc": "Etsimme osaavia insinöörejä, työnjohtajia ja rakennusalan ammattilaisia toimittamaan maailmanluokan projekteja kaikkialla Suomessa.",
    "careers.benefits.badge": "MIKSI RAKENTRA",
    "careers.benefits.h": "Miksi työskennellä meillä",
    "careers.positions.badge": "URATILAISUUDET",
    "careers.positions.h": "Avoimet tehtävät",
    "careers.positions.desc": "Hae tänään liittyäksesi alueellisiin toimistoryhmäteihimme ja työmaan kehitystiimeihin.",
    "careers.positions.applyBtn": "Hae nyt",
    "careers.positions.responsibilities": "Vastuut",
    "careers.positions.requirements": "Vaatimukset",
    "careers.recruitment.badge": "PROSESSI",
    "careers.recruitment.h": "Rekrytointiprosessimme",
    "careers.form.badge": "HAKUKAAVAKE",
    "careers.form.name": "Koko nimi *",
    "careers.form.email": "Sähköpostiosoite *",
    "careers.form.phone": "Puhelinnumero",
    "careers.form.linkedin": "LinkedIn-profiili",
    "careers.form.message": "Hakukirje / Viesti *",
    "careers.form.submit": "Lähetä hakemus",
    "careers.form.submitting": "Lähetetään…",
    "careers.form.close": "Sulje",

    // ─── EQUIPMENT PAGE ───────────────────────────────────────────
    "equipment.hero.badge": "RASKAS KALUSTO",
    "equipment.hero.h1": "Kalustomme &",
    "equipment.hero.h2": "teknologia",
    "equipment.hero.desc": "Rakentra Works ylläpitää laajaa modernia rakennuskaluston laivastoa ja ottaa käyttöön johtavaa älytyömaa-teknologiaa tarkkuuden, nopeuden ja turvallisuuden varmistamiseksi.",
    "equipment.fleet.badge": "KONEKALUSTO",
    "equipment.fleet.h": "Aktiivinen konekalusto",
    "equipment.fleet.desc": "Omistettu ja ylläpidetty korkeimpien toiminnallisten standardien mukaisesti — eliminoiden alihankinnan viivästykset.",
    "equipment.fleet.col.name": "Koneen nimi",
    "equipment.fleet.col.category": "Kategoria",
    "equipment.fleet.col.spec": "Tekniset tiedot",
    "equipment.fleet.col.count": "Käytössä",
    "equipment.fleet.units": "yksikköä",
    "equipment.tech.badge": "INNOVAATIO",
    "equipment.tech.h": "BIM & älytyömaa-teknologia",
    "equipment.tech.desc": "Hyödynnämme pilviyhteistyötä ja IoT-telemetriaa suunnitteluristiriitojen vähentämiseen, materiaalien reaaliaikaiseen seurantaan ja energiamittareiden takaamiseen.",
    "equipment.cta.h": "Tarvitsetko erikoiskalustoa projektiisi?",
    "equipment.cta.desc": "Kalustomme on käytettävissä asiakaskohtaiseen projektitoimitukseen. Ota yhteyttä logistiikkatiimiin tarkistaaksesi kaluston saatavuus.",
    "equipment.cta.btn": "Tarkista kaluston saatavuus",

    // ─── FOOTER ───────────────────────────────────────────────────
    "footer.aboutText": "Edistyksellinen rakennusinfrastruktuuri, asuinrakentaminen ja teollisuuskiinteistöt kaikkialla Suomessa. Turvallisuuden standardointi ja insinöörityön modernisointi vuodesta 2008 lähtien.",
    "footer.cert1": "RALA-sertifioitu urakoitsija (Suomi)",
    "footer.cert2": "ISO 9001 & ISO 14001 -standardit",
    "footer.companyTitle": "Yritys",
    "footer.servicesTitle": "Palvelut",
    "footer.contactTitle": "Ota yhteyttä",
    "footer.officeLabel": "HELSINGIN PÄÄTOIMISTO",
    "footer.officeAddress": "Mannerheimintie 12A, 00100 Helsinki, Suomi",
    "footer.newsletterLabel": "Pysy ajan tasalla alan oivalluksista",
    "footer.newsletterPlaceholder": "Sähköpostiosoitteesi",
    "footer.copyright": "Rakentra Works. Kaikki oikeudet pidätetään. Rekisteröity suomalainen yritys-tunnus: FI2847192-3.",
    "footer.privacy": "Tietosuojakäytäntö",
    "footer.terms": "Palveluehdot",
    "footer.locations": "Yhteystiedot",
    "footer.company.about": "Tietoa meistä",
    "footer.company.leadership": "Johtoryhmä",
    "footer.company.safety": "Turvallisuusstandardit",
    "footer.company.certs": "Sertifioinnit",
    "footer.company.careers": "Urat",
    "footer.services.commercial": "Toimitilarakentaminen",
    "footer.services.residential": "Asuinrakentaminen",
    "footer.services.industrial": "Teollisuuslaitokset",
    "footer.services.infrastructure": "Infrarakentaminen",
    "footer.services.renovation": "Saneeraukset ja kunnostukset",
    "footer.services.pm": "Projektinhallinta",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const stored = window.localStorage.getItem("rakentra-lang");
    return stored === "fi" ? "fi" : "en";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.localStorage.setItem("rakentra-lang", lang);
      document.documentElement.lang = lang;
    }
  }, [lang]);

  const t = (key: string): string =>
    translations[lang][key] ?? translations["en"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
